/**
 * Hand-written row shapes matching supabase/migrations/0001-0010 and the
 * column-level grants in 0002_rls.sql (e.g. `Device` below deliberately
 * omits claim_code_hash/device_identity_hash -- authenticated clients are
 * never granted SELECT on those columns, so they will never appear in a
 * response; modeling them here would just invite writing code that expects
 * a value that can't exist).
 *
 * These are not generated by `supabase gen types` because this project has
 * no live Supabase project yet (see portal README). Once one exists, these
 * can be replaced by generated types -- keep the shapes in sync with the
 * migrations in the meantime.
 */

export type DeviceStatus = "unclaimed" | "claimed" | "active" | "offline";
export type StorageProvider = "s3" | "azure_blob" | "gcs" | "minio";

export interface Organization {
  id: string;
  name: string;
  plan: "free" | "pro" | "enterprise";
  created_at: string;
}

/**
 * organization_members never exposes email -- see list_org_members() /
 * MemberWithEmail below, the only sanctioned way to resolve it.
 */
export interface OrganizationMember {
  org_id: string;
  user_id: string;
  role: OrgRoleValue;
  created_at: string;
}

/** Row shape returned by the list_org_members() RPC (0010_list_org_members.sql). */
export interface MemberWithEmail {
  user_id: string;
  email: string;
  role: OrgRoleValue;
  created_at: string;
}

export interface OrganizationInvite {
  id: string;
  org_id: string;
  email: string;
  role: OrgRoleValue;
  invited_by: string | null;
  created_at: string;
  accepted_at: string | null;
  revoked_at: string | null;
}

/** Row shape returned by the invite_member() RPC. */
export interface InviteMemberResult {
  outcome: "invited" | "added_existing_member";
  invite_id: string | null;
  user_id: string | null;
  email: string;
  role: OrgRoleValue;
}

type OrgRoleValue =
  | "org_admin"
  | "device_admin"
  | "site_manager"
  | "safety_officer"
  | "viewer";

export interface Site {
  id: string;
  org_id: string;
  name: string;
  address: string | null;
  created_at: string;
}

/**
 * The columns `authenticated` is actually granted SELECT on (see the
 * `grant select (...)` list in 0002_rls.sql) -- claim_code_hash and
 * device_identity_hash are intentionally absent both here and in Postgres.
 */
export interface Device {
  id: string;
  org_id: string | null;
  site_id: string | null;
  serial_number: string;
  status: DeviceStatus;
  claimed_at: string | null;
  claimed_by_user_id: string | null;
  last_seen_at: string | null;
  display_name: string | null;
  created_at: string;
}

export interface StorageConfig {
  id: string;
  org_id: string;
  provider: StorageProvider;
  bucket: string;
  region: string | null;
  endpoint: string | null;
  credentials_secret_ref: string;
  created_at: string;
}

/** Row shape returned by the lookup_device_by_claim_code() RPC. */
export interface DeviceLookupResult {
  serial_number: string;
  status: DeviceStatus;
  display_name: string | null;
}

/** Row shape returned by the claim_device() RPC. */
export interface ClaimDeviceResult {
  id: string;
  serial_number: string;
  org_id: string;
  site_id: string | null;
  status: DeviceStatus;
  display_name: string | null;
  claimed_at: string;
}
